/*
*  Crystal Castles - Kerosene melody on ESP32/ESP8266 Anduino modules
*  vGamBIT 
*  v0.1
*  2023
*/

#define NOTE_C4_FREQ 261
#define NOTE_DSHARP3_FREQ 311
#define NOTE_D4_FREQ 293
#define NOTE_ASHARP3_FREQ 233
#define NOTE_A3_FREQ 220
#define NOTE_G3_FREQ 195
#define NOTE_F3_FREQ 174
#define NOTE_F4_FREQ 349

#define NOTE_DURATION 80
#define NEXT_NOTE_DELAY 150

#if defined(ARDUINO_ARCH_ESP32)
static const uint8_t tonePin = 19;
#define LED_BUILTIN 2
#else
static const uint8_t tonePin = D1; // ESP8266 WeMos D1 mini definitions
#endif

// Do some onboard animation if we have some
void delayWithLEDAnimation(int duration) {
  static uint8_t ledDelay = 70;
  digitalWrite(LED_BUILTIN, LOW);
  delay(duration - ledDelay);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(ledDelay);
}

// Generated code so no optimizations ;)
void keroseneTones(int tonePin) {
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY << 1);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY << 1);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY << 1);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY << 1);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_DSHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_A3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_G3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_F4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_D4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_ASHARP3_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
  tone(tonePin, NOTE_C4_FREQ, NOTE_DURATION);
  delayWithLEDAnimation(NEXT_NOTE_DELAY);
}

void setup() {
  pinMode(tonePin, OUTPUT);
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  keroseneTones(tonePin);
#if defined(ARDUINO_ARCH_ESP32)
  esp_deep_sleep_start();
#else
  ESP.deepSleep(0);  // Play once and go sleep
#endif
}
